# Generated by Django 6.0.7 on 2026-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='+254741031179', max_length=15),
            preserve_default=False,
        ),
    ]
