# Generated by Django 6.0.7 on 2026-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('AGENT', 'Agent'), ('READ_ONLY', 'Read-only')], default='AGENT', max_length=10),
        ),
    ]
