# Generated by Django 6.0.7 on 2026-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
